/**
 * Eth2 Beacon Node API
 * API specification for the beacon node, which enables users to query and participate in Ethereum 2.0 phase 0 beacon chain.
 *
 * OpenAPI spec version: v0.12.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.web3j.eth2.client.models


/**
 *
 * @param pubkey The validator's BLS public key, uniquely identifying them. _48-bytes, hex encoded with 0x prefix, case insensitive._
 * @param validatorIndex
 * @param committeeIndex
 * @param committeeLength
 * @param committeesAtSlot
 * @param validatorCommitteeIndex
 * @param slot
 */
data class AttesterDuty(

        /* The validator's BLS public key, uniquely identifying them. _48-bytes, hex encoded with 0x prefix, case insensitive._ */
        val pubkey: kotlin.String? = null,
        val validatorIndex: AllOfAttesterDutyValidatorIndex? = null,
        val committeeIndex: AllOfAttesterDutyCommitteeIndex? = null,
        val committeeLength: AllOfAttesterDutyCommitteeLength? = null,
        val committeesAtSlot: AllOfAttesterDutyCommitteesAtSlot? = null,
        val validatorCommitteeIndex: AllOfAttesterDutyValidatorCommitteeIndex? = null,
        val slot: AllOfAttesterDutySlot? = null
) {
}