/**
 * Eth2 Beacon Node API
 * API specification for the beacon node, which enables users to query and participate in Ethereum 2.0 phase 0 beacon chain.
 *
 * OpenAPI spec version: v0.12.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.web3j.eth2.client.models

/**
 * The [`BeaconBlockBody`](https://github.com/ethereum/eth2.0-specs/blob/v0.12.2/specs/phase0/beacon-chain.md#beaconblockbody) object from the Eth2.0 spec.
 * @param randaoReveal
 * @param eth1Data
 * @param graffiti
 * @param proposerSlashings
 * @param attesterSlashings
 * @param attestations
 * @param deposits
 * @param voluntaryExits
 */
data class BeaconBlockBody(

        val randaoReveal: AllOfBeaconBlockBodyRandaoReveal? = null,
        val eth1Data: BeaconStateEth1Data? = null,
        val graffiti: String? = null,
        val proposerSlashings: Array<Body3>? = null,
        val attesterSlashings: Array<Body2>? = null,
        val attestations: Array<Body1>? = null,
        val deposits: Array<BeaconBlockBodyDeposits>? = null,
        val voluntaryExits: Array<Body4>? = null
) 