/**
 * Eth2 Beacon Node API
 * API specification for the beacon node, which enables users to query and participate in Ethereum 2.0 phase 0 beacon chain.
 *
 * OpenAPI spec version: v0.12.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.web3j.eth2.client.models

/**
 *
 * @param peerId Cryptographic hash of a peer’s public key. [Read more](https://docs.libp2p.io/concepts/peer-id/)
 * @param enr Ethereum node record. [Read more](https://eips.ethereum.org/EIPS/eip-778)
 * @param p2pAddresses
 * @param discoveryAddresses
 * @param metadata
 */
data class NetworkIdentity(

        /* Cryptographic hash of a peer’s public key. [Read more](https://docs.libp2p.io/concepts/peer-id/) */
        val peerId: String? = null,
        /* Ethereum node record. [Read more](https://eips.ethereum.org/EIPS/eip-778) */
        val enr: String? = null,
        val p2pAddresses: Array<AllOfNetworkIdentityP2pAddressesItems>? = null,
        val discoveryAddresses: Array<AllOfNetworkIdentityDiscoveryAddressesItems>? = null,
        val metadata: NetworkIdentityMetadata? = null
) 