/**
 * Eth2 Beacon Node API
 * API specification for the beacon node, which enables users to query and participate in Ethereum 2.0 phase 0 beacon chain.
 *
 * OpenAPI spec version: v0.12.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.web3j.eth2.client.models


/**
 *
 * @param pubkey The validator's BLS public key, uniquely identifying them. _48-bytes, hex encoded with 0x prefix, case insensitive._
 * @param withdrawalCredentials
 * @param effectiveBalance
 * @param slashed Was validator slashed (not longer active).
 * @param activationEligibilityEpoch
 * @param activationEpoch
 * @param exitEpoch
 * @param withdrawableEpoch
 */
data class ValidatorResponseValidator(

        /* The validator's BLS public key, uniquely identifying them. _48-bytes, hex encoded with 0x prefix, case insensitive._ */
        val pubkey: kotlin.String? = null,
        val withdrawalCredentials: AllOfValidatorResponseValidatorWithdrawalCredentials? = null,
        val effectiveBalance: AllOfValidatorResponseValidatorEffectiveBalance? = null,
        /* Was validator slashed (not longer active). */
        val slashed: kotlin.Boolean? = null,
        val activationEligibilityEpoch: AllOfValidatorResponseValidatorActivationEligibilityEpoch? = null,
        val activationEpoch: AllOfValidatorResponseValidatorActivationEpoch? = null,
        val exitEpoch: AllOfValidatorResponseValidatorExitEpoch? = null,
        val withdrawableEpoch: AllOfValidatorResponseValidatorWithdrawableEpoch? = null
) {
}