/**
 * Eth2 Beacon Node API
 * API specification for the beacon node, which enables users to query and participate in Ethereum 2.0 phase 0 beacon chain.
 *
 * OpenAPI spec version: v0.12.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.web3j.eth2.api.models


/**
 * The [`DepositData`](https://github.com/ethereum/eth2.0-specs/blob/v0.12.2/specs/phase0/beacon-chain.md#depositdata) object from the Eth2.0 spec.
 * @param pubkey The validator's BLS public key, uniquely identifying them. _48-bytes, hex encoded with 0x prefix, case insensitive._
 * @param withdrawalCredentials
 * @param amount
 * @param signature
 */
data class BeaconBlockBodyData(

        /* The validator's BLS public key, uniquely identifying them. _48-bytes, hex encoded with 0x prefix, case insensitive._ */
        val pubkey: String? = null,
        val withdrawalCredentials: AllOfBeaconBlockBodyDataWithdrawalCredentials? = null,
        val amount: AllOfBeaconBlockBodyDataAmount? = null,
        val signature: AllOfBeaconBlockBodyDataSignature? = null
) 