/**
 * Eth2 Beacon Node API
 * API specification for the beacon node, which enables users to query and participate in Ethereum 2.0 phase 0 beacon chain.
 *
 * OpenAPI spec version: v0.12.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.web3j.eth2.api.models

/**
 *
 * @param previousJustified
 * @param currentJustified
 * @param finalized
 */
data class GetStateFinalityCheckpointsResponseData(

        val previousJustified: Ethv1beaconpoolattestationsDataSource? = null,
        val currentJustified: Ethv1beaconpoolattestationsDataSource? = null,
        val finalized: Ethv1beaconpoolattestationsDataSource? = null
) 